version: '3.0'

services:
    server:
        container_name: server
        build:
            context: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: npm run start:dev
        depends_on:
            - db
        restart: always
    db:
        container_name: db
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=my_db
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3307:3306'
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    db:
