version: '3.0'

services:
    server:
        container_name: server
        build:
            context: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: sh -c "npm run migration:run && npm run start:dev"
        restart: always
        depends_on:
            - db
    db:
        container_name: db
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3307:3306'

volumes:
    db_volume:
